### ISSUE TITLE
Auth0 returning 400

### ISSUE THREAD

**Issue by zpatrick** [quintilesims/d.ims.io#31]
I'm encountering unexpected 400 errors from the `Auth0Manager` while stress testing.

Debug output from the API: 
```
2017/06/27 20:42:18 [DEBUG] Request GET /v2/ did not contain basic auth
2017/06/27 20:42:18 [DEBUG] Request GET /v1/_ping did not contain basic auth
2017/06/27 20:42:18 [ERROR] Authenticator encountered an unexpected error: Invalid status code: 400
```

I tracked the error down to [here](https://github.com/quintilesims/d.ims.io/blob/develop/auth/auth0_manager.go#L84).  I can send you the Auth0 credentials I'm using in Slack. 

I'd recommend using a custom [rclient.ResponseReader](https://github.com/zpatrick/rclient/blob/master/examples/handle_github_error/main.go#L24) for debugging this issue.

**Comment by tlake** [comment]
All of my attempts to repro this issue have failed, so I'll close it for now and we can reopen it if the problem resurfaces. 

ZP originally encountered the issue by submitting bad authentication My attempts to repro were variations of the following:
- Stand up local instance of service: `$ go run main.go`
- Base64-encode some bad credentials: `$ export BAD_AUTH=$(echo -n bad:creds | base64)`
- Hit the local instance with bad creds: `$ curl -H "Authorization: Basic ${BAD_AUTH}" "localhost:9090"`

These calls always resulted in the expected 401 response.
