### ISSUE TITLE
Cannot retrieve repository whose name contains slashes

### ISSUE THREAD

**Issue by tlake** [quintilesims/d.ims.io#43]
# About
Currently, we cannot access a repository whose name contains slashes, like so: `docker.ims.io/repository/tlake/test/with/slashes`

I think it's probably fine for that to be our contract, but if so, there are a couple of things that should be done:

1. Explicitly call out this behavior, at least in the README
2. Throw an error/warning/information message at `POST docker.ims.io/repository/owner ; body={"name":"string"}` if either `owner` or `string` contains a slash character
3. Have a conversion plan for repos on the older d.ims.io (which seems to allow these slashes)

The older d.ims.io seemed to allow this convention, as there are some repos with slashes in their names that have been migrated to docker.ims.io and which cannot currently be accessed from the new docker.ims.io.

If we _do_ want to allow this convention in docker.ims.io, we should fix this behavior as a bug. Whadday'all think?

# Repro

### Create two test repositories:
- POST `docker.ims.io/repository/tlake` body=`{"name":"test-without-slashes"}`
- POST `docker.ims.io/repository/tlake` body=`{"name":"test/with/slashes"}`

Both creation commands complete properly.

### Describe those repositories:
- GET `docker.ims.io/repository/tlake/test-without-slashes`
- GET `docker.ims.io/repository/tlake/test/with/slashes`

The first one succeeds, but the second fails with `404 page not found`.

**Comment by zpatrick** [comment]
We are already enforcing our own paradigm by requiring that each repo has an `owner`. In that regard, I think throwing an error when the name has slashes makes sense.
