### ISSUE TITLE
Improve auth 

### ISSUE THREAD

**Issue by zpatrick** [quintilesims/d.ims.io#61]
* Move caching logic from the auth0_manager to the [auth decorator](https://github.com/quintilesims/d.ims.io/blob/develop/controllers/auth.go#L10)
* Use sha256 for hash key
* Immediately return 401 on cached invalid user:pass hashes instead of doing a delay penalty.

**Comment by sesh-kebab** [comment]
Also logging request ip might help track down where the request is coming from.
